name: Python Tests

on:
  [push]

jobs:
  tests:
    name: Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pipenv
          python -V
          pipenv install
      - name: Run tests
        run: pipenv run python manage.py test
